name: Build and deploy

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
        inputs:
            type:
                description: 'Camus type'
                required: true
                default: 'release'
                type: choice
                options:
                    - test
                    - release

            version:
                description: 'Camus version'
                required: false
                type: string
                default: 'v11.0.0'

permissions:
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-24.04
        container:
            image: docker.io/ubuntu:24.04
        steps:
            -   uses: actions/checkout@v4
            -   name: Install dependencies
                run: |
                    apt update -y
                    apt install -y curl jq unzip libarchive-dev

            -   name: Install Camus-release
                env:
                    CAMUS_VERSION: ${{ github.event.inputs.version || 'v11.0.0' }}
                if: github.event.inputs.type != 'test'
                run: |
                    curl -Lo camus.deb https://github.com/o8x/camus/releases/download/${CAMUS_VERSION}/camus-${CAMUS_VERSION}_linux6.17.0-1020-azure-x86_64.deb
                    dpkg -i camus.deb

            -   name: Install Camus-test
                if: github.event.inputs.type == 'test'
                run: |
                    RUN_ID=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
                        "https://api.github.com/repos/o8x/camus/actions/runs?status=success&per_page=1" \
                        | jq -r '.workflow_runs[0].id')
                    DOWNLOAD_URL=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
                        "https://api.github.com/repos/o8x/camus/actions/runs/$RUN_ID/artifacts" \
                        | jq -r '.artifacts[1].archive_download_url')
                    
                    echo "Camus from action=https://github.com/o8x/camus/actions/runs/$RUN_ID file=$DOWNLOAD_URL"
                
                    curl -L -o camus.zip -H "Authorization: Bearer ${{ github.token }}" "$DOWNLOAD_URL"
                    unzip camus.zip && rm -f camus.zip 
                    dpkg -i *.deb

            -   name: Build
                run: |
                    echo "GITHUB_ACTION_URL=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|g" >> .env
                    camus -iI
                    camus -d

            -   name: Setup Pages
                uses: actions/configure-pages@v5

            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v3
                with:
                    path: './html'

            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v5
